language: node_js
node_js:
  - "5.5"
  - "4.2"
  - "0.12"
  - "0.10"
git:
  depth: 10
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
    - sudo add-apt-repository -y ppa:mapnik/nightly-trunk
    - sudo apt-get update -qq
    - sudo apt-get -y install libmapnik=3.0.0* mapnik-utils=3.0.0* libmapnik-dev=3.0.0* mapnik-input-plugin-postgis=3.0.0* mapnik-input-plugin-sqlite=3.0.0* mapnik-input-plugin-gdal=3.0.0* mapnik-input-plugin-ogr=3.0.0*
install:
    - npm install
    - npm test
